name: DB
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2
    - name: login to rds
      run: |
        
        bash s.sh
        
        echo $?
    - name: dump sql
      run: |
        MYSQL_USERNAME="admin"
        MYSQL_PASSWORD="password"
        MYSQL_HOST="test-db.cvsned4gvlis.ap-south-1.rds.amazonaws.com"
        mysql -u "$MYSQL_USERNAME" -p"$MYSQL_PASSWORD" -h "$MYSQL_HOST"  test < db.sql
    - name: check db status
      run: |
        bash script.sh
