name: DB
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2
    - name: login to rds
      run: |
        MYSQL_USERNAME="admin"
        MYSQL_PASSWORD="password"
        mysql -u "$MYSQL_USERNAME" -p"$MYSQL_PASSWORD" -h deliveryguru.cvsned4gvlis.ap-south-1.rds.amazonaws.com
        echo $?
    - name: dump sql
      run: |
        mysql -u "$MYSQL_USERNAME" -p"$MYSQL_PASSWORD" -h deliveryguru.cvsned4gvlis.ap-south-1.rds.amazonaws.com test < db.sql
    - name: check db status
      run: |
        bash script.sh
