name: DB
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2
    - name: login to rds
      run: |
        
        bash s.sh
        
        echo $?
    - name: dump sql
      run: |
        MYSQL_USERNAME="${{ secret.MYSQL_USERNAME }}"
        MYSQL_PASSWORD="${{ secret.MYSQL_PASSWORD }}"
        MYSQL_HOST="${{ secret.MYSQL_HOST }}"
        mysql -u "$MYSQL_USERNAME" -p"$MYSQL_PASSWORD" -h "$MYSQL_HOST"  test < database.sql
    - name: check db status
      run: |
        bash script.sh
